CREATE SCHEMA ZELADORIA_PUBLICA;

USE ZELADORIA_PUBLICA;

CREATE TABLE Cidadao 
( 
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,  
 Nome VARCHAR(100) NOT NULL,  
 Pontos INT UNSIGNED NOT NULL
); 

CREATE TABLE Melhoria 
( 
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,  
 Descricao LONGTEXT NOT NULL,
 Status VARCHAR(20) NOT NULL,  
 Apoio INT DEFAULT 0 NOT NULL,  
 Endereco VARCHAR(255) NOT NULL, 
 Resposta VARCHAR(255) NOT NULL,
 idCidadao INT UNSIGNED NOT NULL,
 idCategoria INT UNSIGNED NOT NULL
); 

CREATE TABLE Acao 
( 
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,  
 Descricao Longtext,  
 Apoio INT UNSIGNED NOT NULL,  
 Endereco VARCHAR(255) NOT NULL,
 Status VARCHAR(20) NOT NULL,
 Criador INT UNSIGNED NOT NULL);

CREATE TABLE Categoria 
( 
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,  
 nome VARCHAR(30) NOT NULL 
); 

CREATE TABLE Voluntario 
( 
 id INT PRIMARY KEY AUTO_INCREMENT, 
 idCidadao INT UNSIGNED NOT NULL,  
 idAcao INT UNSIGNED NOT NULL
); 

ALTER TABLE Melhoria ADD FOREIGN KEY(idCidadao) REFERENCES Cidadao (id);
ALTER TABLE Melhoria ADD FOREIGN KEY(idCategoria) REFERENCES Categoria (id);
ALTER TABLE Acao ADD FOREIGN KEY(idCategoria) REFERENCES Categoria (id);
ALTER TABLE Voluntario ADD FOREIGN KEY(idCidadao) REFERENCES Cidadao (id);
ALTER TABLE Voluntario ADD FOREIGN KEY(idAcao) REFERENCES Acao (id);